# Generated by Django 4.1 on 2022-08-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
                ('destino', models.CharField(choices=[('101', '101'), ('201', '201'), ('301', '301'), ('401', '401'), ('501', '501')], max_length=3)),
                ('data', models.DateTimeField(blank='True', null=True)),
            ],
        ),
    ]
